### ISSUE TITLE
SVG for some gerbers not correctly displayed in Inkscape

### ISSUE THREAD

**Issue by andersonls** [tracespace/gerber-to-svg#40]
Hello, I'm having problems with some generated SVG using this tool. The generated SVGs are missing some elements with some gerbers. Opening the SVG with Inkscape i found that the elements seems to be being draw but with inverted colors.

Below you can find the Gerber used and the generated SVG (with gerber2svg) and PNG (with gerbv)

Gerber file: [gerber.txt](https://github.com/tracespace/gerber-to-svg/files/1660579/gerber.txt)

Excpected result (generated with gerbv):  ![excpected](https://user-images.githubusercontent.com/1561038/35343244-4c2fe002-0111-11e8-8360-9c3fac9c9a36.png)

Actual result (generated with gerber2svg): [generated-svg.txt](https://github.com/tracespace/gerber-to-svg/files/1660583/generated-svg.txt)

**Comment by mcous** [comment]
Hi, sorry to hear you're having an issue! After spending a few minutes looking for differences between the gerbv and `gerber-to-svg` output, I was unable to find anything missing. Would you mind annotating the png below to point them out for me?

`gerber-to-svg` output run through [`svg2png`](https://github.com/domenic/svg2png):

![gerber](https://user-images.githubusercontent.com/2963448/35355186-86a0cc16-011a-11e8-940b-2f4f74fb6448.png)

**Comment by andersonls** [comment]
That's weird, it seems like **inkscape** is not converting the SVG properly.

Do you know any other tool for converting SVG to high resolution bitmaps (2000 DPI and higher)? 

**svg2png** is taking almost 2 minutes to convert in 2000 DPI while **inkscape** takes 35 sec.

PNG generated with inkscape:
![test](https://user-images.githubusercontent.com/1561038/35399906-90a8c39a-01dc-11e8-860d-668b76768eac.png)

**Comment by kasbah** [comment]
We've seen Inkscape compatibility issues before: https://github.com/tracespace/pcb-stackup/issues/29. If you can pin down the exact issue I'd be interested as I also use Inkscape to convert to PNG on [Kitspace](https://kitspace.org).

**Comment by andersonls** [comment]
I highlighted the images bellow the elements that are missing when converting to PNG with Inkscape. If I open the SVG with Inkscape and ungroup the element you can see that they are present but for some reason Inkscape is drawing a black polygon on top of them.

Inskcape PNG missing elements: 
![inkscape](https://user-images.githubusercontent.com/1561038/35401281-34676628-01e0-11e8-99c0-06e67fda1299.png)

Inkscape interface:
![inkscape2](https://user-images.githubusercontent.com/1561038/35401320-4c504c6e-01e0-11e8-823d-9ce041f2be26.png)

Excpected result using gerbv:
![excpected](https://user-images.githubusercontent.com/1561038/35401330-55978530-01e0-11e8-8b68-cd685a67c218.png)

**Comment by mcous** [comment]
@andersonls the SVG output of `gerber-to-svg` appears to be correct. Like @kasbah said, this seems to be a problem with Inkscape not displaying the SVGs properly. I'm not an Inkscape user myself, but PRs to improve Inkscape compatibility are definitely welcome and helpful.

As for SVG to PNG conversion: `svg2png` uses phantomJS, which isn't my favorite thing in the world. You may have luck using [electron](https://electronjs.org/) or [Puppeteer](https://github.com/GoogleChrome/puppeteer), both of which could (theoretically) use Chrome to generate a PNG.

**Comment by andersonls** [comment]
Ok, thank you. I just started messing up with RS-274X and SVG, but if I can find the issue i'll submit a PR.
